# -*- coding: utf-8 -*-
"""Prompting_all_models_new_code_Laura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f85Fg4QkLBFZq9RZnPFeLoCcrqSipd93
"""

##NOTE: ONLY RUN THE CELL WITH THE LANGUAGE PROMPTS OF THE MODEL BEING RUN, DO NOT RUN ALL

import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForSeq2Seq
)

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, GenerationConfig
import torch

import pandas as pd
from datetime import datetime

#Model information
model_name = "aoifeodriscoll/ger-model-test-learnerdataset" #change to different models
language = "German" #change as required
proficiency = "beginner" #change as required

#Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

#Load model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None
)

# Create pipeline
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1
)

# Define default generation config (you can reuse it)
gen_config = GenerationConfig(
    max_new_tokens=300,
    min_new_tokens=250,
    temperature=0.7,
    do_sample=True,
    pad_token_id=tokenizer.eos_token_id,
    eos_token_id=None,
    return_full_text=False
)

print("Model and pipeline loaded. Ready to generate!")

#SPANISH MODEL
prompts_SPA = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part en diversas actividades y aficiones. Write an article para tu periódico local describing the activities you can do in your town durante el fin de semana."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "Tu amiga, Sophia, has emailed you about her recent holiday. Write an email to her, describiéndole tus vacaciones favoritas."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "Tu revista local is holding a competition for articles about the question ‘Big family or small family’. Escribe un artículo sobre tu familia. You should include whether you have a big or small family, y cuál prefieres."
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Spanish."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Spanish."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Spanish."
    }
]

results_SPA = []

for p in prompts_SPA:

    full_prompt_SPA = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_SPA, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_SPA.append(row)

    df = pd.DataFrame(results_SPA)

output_file = "spanishgenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

print(f"Saved to {output_file}")

#FRENCH MODEL
prompts_FRE = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in différentes activités et loisirs. Write an article pour votre journal local describing the activities you can do in your town le week-end."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "Votre amie, Sophia, has emailed you about her recent holiday. Write an email to her et décrivez vos vacances préférées."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "Votre magazine local is holding a competition for articles about the question 'Big family or small family'. Écrivez un article sur votre famille. You should include whether you have a big or small family, et laquelle vous préférez."
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in French."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in French."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in French."
    }
]

results_FRE = []

for p in prompts_FRE:

    full_prompt_FRE = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_FRE, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_FRE.append(row)

    df = pd.DataFrame(results_FRE)

output_file = "frenchgenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

#GERMAN MODEL
prompts_GER = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people an verschiedenen Aktivitäten und Hobbys teilzunehmen. Write an article für Ihre Lokalzeitung describing the activities you can do in your town am Wochenende."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "Ihre Freundin, Sophia, has emailed you about her recent holiday. Write an email to her und beschreiben Sie Ihren schönsten Urlaub, den Sie je gemacht haben."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "Ihre lokale Zeitschrift is holding a competition for articles about the question 'Big family or small family'. Schreiben Sie einen Artikel über Ihre Familie. You should include whether you have a big or small family, und was Sie bevorzugen."
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in German."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in German."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in German."
    }
]

results_GER = []

for p in prompts_GER:

    full_prompt_GER = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_GER, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_GER.append(row)

    df = pd.DataFrame(results_GER)

output_file = "germangenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

#POLISH MODEL
prompts_POL = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part w różnych zajęciach i hobby. Write an article do lokalnej gazety describing the activities you can do in your town w weekendy."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "Twoja przyjaciółka, Sophia, has emailed you about her recent holiday. Write an email to her, w którym opiszesz swoje dotychczasowe ulubione wakacje."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "Twoja lokalna gazeta is holding a competition for articles about the question 'Big family or small family'. Napisz artykuł o swojej rodzinie. You should include whether you have a big or small family, i którą z nich preferujesz."
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Polish."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Polish."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Polish."
    }
]

results_POL = []

for p in prompts_POL:

    full_prompt_POL = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_POL, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_POL.append(row)

    df = pd.DataFrame(results_POL)

output_file = "polishgenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

#TURKISH MODELS
prompts_TUR = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town insanların farklı etkinliklere ve hobilere katılmasını istiyor. Yerel gazete için, write an article describing the activities you can do in your town hafta sonu."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "Arkadaşın, Sophia, has emailed you about her recent holiday. Write an email to her, en sevdiğin tatili anlatan."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "Yerel derginiz is holding a competition for articles about the question 'Big family or small family'. Aileniz hakkında bir makale yazın. You should include whether you have a big or small family,  ve hangisini tercih ettiğinizi de yazmalısınız."
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Turkish."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Turkish."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Turkish."
    }
]

results_TUR = []

for p in prompts_TUR:

    full_prompt_TUR = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_TUR, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_TUR.append(row)

    df = pd.DataFrame(results_TUR)

output_file = "turkishgenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

#ARABIC MODELS
prompts_ARA = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part (في مختلف الأنشطة والهوايات). Write an article (لصحيفتك المحلية) describing the activities you can do in your town (في عطلة نهاية الأسبوع)."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "(صديقتك), Sophia, has emailed you about her recent holiday. Write an email to her, (تصف عطلتك المفضلة التي ذهبتَ/ذهبتِ إليها)."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "(مجلتك المحلية) is holding a competition for articles about the question ‘Big family or small family’. (اكتب مقالًا عن عائلتك.) You should include whether you have a big or small family, (وأيّهما تفضّل)."
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Arabic."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Arabic."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Arabic."
    }
]

results_ARA = []

for p in prompts_ARA:

    full_prompt_ARA = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_ARA, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_ARA.append(row)

    df = pd.DataFrame(results_ARA)

output_file = "arabicgenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

#CHINESE MODELS
prompts_CHI = [
    {
        "prompt_id": "A1",
        "prompt_style": "basic",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend."
    },
    {
        "prompt_id": "B1",
        "prompt_style": "basic",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on."
    },
    {
        "prompt_id": "C1",
        "prompt_style": "basic",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer."
    },
    {
        "prompt_id": "A2",
        "prompt_style": "mixed",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part 在不同的活动和爱好中. Write an article 为您的当地报纸 describing the activities you can do in your town 周末."
    },
    {
        "prompt_id": "B2",
        "prompt_style": "mixed",
        "prompt_topic": "holiday",
        "instruction": "你的朋友, Sophia, has emailed you about her recent holiday. Write an email to her, 描述一下你最喜欢的假期."
    },
    {
        "prompt_id": "C2",
        "prompt_style": "mixed",
        "prompt_topic": "family",
        "instruction": "你当地的杂志 is holding a competition for articles about the question ‘Big family or small family’. 写一篇关于你家庭的文章. You should include whether you have a big or small family, 你更喜欢哪一个"
    },
    {
        "prompt_id": "A3",
        "prompt_style": "l2t",
        "prompt_topic": "hobbies",
        "instruction": "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Chinese."
    },
    {
        "prompt_id": "B3",
        "prompt_style": "l2t",
        "prompt_topic": "holiday",
        "instruction": "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Chinese."
    },
    {
        "prompt_id": "C3",
        "prompt_style": "l2t",
        "prompt_topic": "family",
        "instruction": "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Chinese."
    }
]

results_CHI = []

for p in prompts_CHI:

    full_prompt_CHI = (
        "### Instruction:\n"
        f"{p['instruction']}\n\n"
        "### Response:\n"
    )

    output = generator(full_prompt_CHI, generation_config=gen_config)

    generated_text = output[0]["generated_text"].split("### Response:")[-1].strip()

    row = {
        "model_name": model_name,
        "language": language,
        "proficiency": proficiency,
        "prompt_id": p["prompt_id"],
        "prompt_style": p["prompt_style"],
        "prompt_topic": p["prompt_topic"],
        "generated_text": generated_text,
    }

    results_CHI.append(row)

    df = pd.DataFrame(results_CHI)

output_file = "chinesegenerations.csv"
df.to_csv(output_file, index=False, encoding="utf-8")