# -*- coding: utf-8 -*-
"""Laura copy 3 of code - gpt2 mini and alpaca

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8I9Z1A_sxvV-3Lc13tTj-e-FCjjgB__
"""

# ===== TRUE INSTRUCTION TUNING (MASK PROMPT LOSS) – END-TO-END =====
# Works for causal LM models (GPT-style, OPT, LLaMA, etc.)
# Masks loss so model ONLY learns from assistant / response tokens

import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForSeq2Seq
)

# -----------------------------
# CONFIG
# -----------------------------
MODEL_NAME = "erwanf/gpt2-mini"          # change to your model
MAX_LENGTH = 512
OUTPUT_DIR = "./inst_tuned_model"
IGNORE_INDEX = -100

# -----------------------------
# LOAD TOKENIZER + MODEL
# -----------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

tokenizer.padding_side = "right"

# GPT2 has no pad token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# Resize embeddings if tokenizer changed
model.resize_token_embeddings(len(tokenizer))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print("Loaded model on:", device)

# -----------------------------
# LOAD DATASET
# Expected fields:
#   instruction
#   response
# -----------------------------
dataset = load_dataset("tatsu-lab/alpaca", split="train")

print(dataset.column_names)

print(len(dataset))

# remove the rows with input:
# Keep only rows where input is empty
dataset = dataset.filter(lambda example: example['input'] == "")

# Check
print(len(dataset))
print(dataset.column_names)

# rename dataset columns:
dataset = dataset.rename_columns({
    "instruction": "instruction",
    "output": "response",
})

# RUN THIS ONE!
def format_example(example):
    prompt = f"### Instruction:\n{example['instruction']}\n\n### Response:\n"
    answer = example["response"]

    # Tokenize prompt (never truncate)
    prompt_tokens = tokenizer(
        prompt,
        add_special_tokens=False
    )
    prompt_len = len(prompt_tokens["input_ids"])

    # Compute available space for answer
    max_response_len = MAX_LENGTH - prompt_len - 1  # EOS

    if max_response_len <= 0:
        raise ValueError("Prompt too long for MAX_LENGTH")

    # Tokenize answer (truncate ONLY here)
    answer_tokens = tokenizer(
        answer,
        add_special_tokens=False,
        truncation=True,
        max_length=max_response_len
    )

    # Concatenate
    input_ids = (
        prompt_tokens["input_ids"]
        + answer_tokens["input_ids"]
        + [tokenizer.eos_token_id]
    )

    attention_mask = [1] * len(input_ids)

    # Labels: mask prompt tokens
    labels = input_ids.copy()
    labels[:prompt_len] = [IGNORE_INDEX] * prompt_len

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

dataset = dataset.map(
    format_example,
    remove_columns=dataset.column_names
)

print(dataset.column_names)

# CHECK!
ex = dataset[0]
print(tokenizer.decode(ex["input_ids"], skip_special_tokens=False))

# -----------------------------
# SAFETY CHECK (prevents CUDA assert)
# -----------------------------
vocab_size = model.get_input_embeddings().weight.shape[0]

def validate(example):
    for t in example["input_ids"]:
        assert 0 <= t < vocab_size, f"Token id {t} outside vocab"
    return example

dataset = dataset.map(validate)

# -----------------------------
# DATA COLLATOR
# -----------------------------
collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    padding=True,
)

# -----------------------------
# TRAINING ARGS
# -----------------------------
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_strategy="steps",
    logging_steps=10,  # log more frequently
    save_steps=500,
    bf16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

# -----------------------------
# TRAINER
# -----------------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=collator,
)

# -----------------------------
# TRAIN
# -----------------------------
trainer.train()

# -----------------------------
# SAVE MODEL
# -----------------------------
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training complete.")

print(len(dataset))

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. "
    "Write an email to her, describing your favourite holiday you have been on.\n\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Write an email to your brother, describing your favourite holiday you have been on.\n\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens = 250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Instruction: Write a newspaper article about what activities you can do in your town at the weekend.\n\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=200, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])