# -*- coding: utf-8 -*-
"""Laura instruction tuning alpaca English + French (31322 rows total)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyhxjGhGQHgB5LJAxXo5oULFPRxMOpU9
"""

# ===== TRUE INSTRUCTION TUNING (MASK PROMPT LOSS) – END-TO-END =====
# Works for causal LM models (GPT-style, OPT, LLaMA, etc.)
# Masks loss so model ONLY learns from assistant / response tokens

import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForSeq2Seq
)

# -----------------------------
# CONFIG
# -----------------------------
MODEL_NAME = "catherinearnett/B-GPT_es_en_simultaneous"          # change to your model
MAX_LENGTH = 128
OUTPUT_DIR = "./inst_tuned_model"
IGNORE_INDEX = -100

# -----------------------------
# LOAD TOKENIZER + MODEL
# -----------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

tokenizer.padding_side = "right"

# GPT2 has no pad token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)

# Resize embeddings if tokenizer changed
model.resize_token_embeddings(len(tokenizer))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print("Loaded model on:", device)

# -----------------------------
# LOAD DATASET
# Expected fields:
#   instruction
#   response
# -----------------------------
from datasets import load_dataset, concatenate_datasets

alpaca_english = load_dataset("tatsu-lab/alpaca", split="train")
alpaca_french = load_dataset("jpacifico/French-Alpaca-dataset-Instruct-110K", split="train")

print(alpaca_english.column_names)
print(alpaca_french.column_names)

print(len(alpaca_english))
print(len(alpaca_french))

# remove the rows with input:
# Keep only rows where input is empty
alpaca_english = alpaca_english.filter(lambda example: example['input'] == "")

# Check
print(len(alpaca_english))
print(alpaca_english.column_names)

# normalise alpaca french:
import unicodedata

def normalize_example(example):
    for col in ["instruction", "input", "output"]:
        if col in example and example[col] is not None:
            example[col] = unicodedata.normalize("NFKC", example[col])
    return example

alpaca_french = alpaca_french.map(normalize_example)

# remove the rows with input:
# Keep only rows where input is empty
alpaca_french = alpaca_french.filter(
    lambda example: example.get("input") is None
                    or example["input"].strip() == ""
                    or example["input"].strip().lower() == "aucun"
)
# Check
print(len(alpaca_french))
print(alpaca_french.column_names)

# rename dataset columns:
alpaca_english = alpaca_english.rename_columns({
    "instruction": "instruction",
    "output": "response",
})

# rename dataset columns:
alpaca_french = alpaca_french.rename_columns({
    "instruction": "instruction",
    "output": "response",
})

# shuffle each
alpaca_english = alpaca_english.shuffle(seed=42)
alpaca_french = alpaca_french.shuffle(seed=42)

min_size = min(len(alpaca_english), len(alpaca_french))

alpaca_english = alpaca_english.select(range(min_size))
alpaca_french = alpaca_french.select(range(min_size))

print(len(alpaca_english))
print(len(alpaca_french))

# randomly halve each
half_en = len(alpaca_english) // 2
half_fr = len(alpaca_french) // 2

alpaca_english = alpaca_english.select(range(half_en))
alpaca_french = alpaca_french.select(range(half_fr))

dataset = concatenate_datasets([alpaca_english, alpaca_french])
dataset = dataset.shuffle(seed=42)

print(len(dataset))

# RUN THIS ONE!
def format_example(example):
    prompt = f"### Instruction:\n{example['instruction']}\n\n### Response:\n"
    answer = example["response"]

    # Tokenize prompt (never truncate)
    prompt_tokens = tokenizer(
        prompt,
        add_special_tokens=False
    )
    prompt_len = len(prompt_tokens["input_ids"])

    # Compute available space for answer
    max_response_len = MAX_LENGTH - prompt_len - 1  # EOS

    if max_response_len <= 0:
        raise ValueError("Prompt too long for MAX_LENGTH")

    # Tokenize answer (truncate ONLY here)
    answer_tokens = tokenizer(
        answer,
        add_special_tokens=False,
        truncation=True,
        max_length=max_response_len
    )

    # Concatenate
    input_ids = (
        prompt_tokens["input_ids"]
        + answer_tokens["input_ids"]
        + [tokenizer.eos_token_id]
    )

    attention_mask = [1] * len(input_ids)

    # Labels: mask prompt tokens
    labels = input_ids.copy()
    labels[:prompt_len] = [IGNORE_INDEX] * prompt_len

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }

dataset = dataset.map(
    format_example,
    remove_columns=dataset.column_names
)

print(dataset.column_names)

# CHECK!
ex = dataset[0]
print(tokenizer.decode(ex["input_ids"], skip_special_tokens=False))

# -----------------------------
# SAFETY CHECK (prevents CUDA assert)
# -----------------------------
vocab_size = model.get_input_embeddings().weight.shape[0]

def validate(example):
    for t in example["input_ids"]:
        assert 0 <= t < vocab_size, f"Token id {t} outside vocab"
    return example

dataset = dataset.map(validate)

# -----------------------------
# DATA COLLATOR
# -----------------------------
collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    padding=True,
)

# -----------------------------
# TRAINING ARGS
# -----------------------------
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_strategy="steps",
    logging_steps=100,  # log more frequently
    save_steps=500,
    bf16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

# -----------------------------
# TRAINER
# -----------------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=collator,
)

# -----------------------------
# TRAIN
# -----------------------------
trainer.train()

# -----------------------------
# SAVE MODEL
# -----------------------------
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training complete.")

model.push_to_hub("lgb35/B-GPT-es-fineweb-intermediate-alpacaEnglish")
tokenizer.push_to_hub("lgb35/B-GPT-es-fineweb-intermediate-alpacaEnglish")

import pandas as pd

logs = pd.DataFrame(trainer.state.log_history)
logs.to_csv(f"{OUTPUT_DIR}/training_logs.csv", index=False)

logs.head()

print(len(dataset))

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. "
    "Write an email to her, describing your favourite holiday you have been on.\n\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# A1
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend.\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# B1
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on.\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# C1
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer.\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# A2
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your town wants people to take part en diversas actividades y aficiones. Write an article para tu periódico local describing the activities you can do in your town durante el fin de semana.\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend.\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Write an email to your brother, describing your favourite holiday you have been on.\n\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens = 250, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])

# CHANGE MAX LENGTH TO MAX NEW TOKENS!
from transformers import pipeline

prompt = (
    "### Instruction:\n"
    "Write a newspaper article about what activities you can do in your town at the weekend.\n\n"
    "### Response:\n"
)

generator = pipeline('text-generation', model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)
output = generator(prompt, max_new_tokens=300, min_new_tokens=200, temperature=0.7, do_sample=True, pad_token_id=tokenizer.eos_token_id)
print(output[0]['generated_text'])
