# -*- coding: utf-8 -*-
"""Copy of Laura prompting code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMGCdZrhg6plRgmDq7Anq4D6C83nTauq
"""

# ===== TRUE INSTRUCTION TUNING (MASK PROMPT LOSS) – END-TO-END =====
# Works for causal LM models (GPT-style, OPT, LLaMA, etc.)
# Masks loss so model ONLY learns from assistant / response tokens

import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForSeq2Seq
)

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, GenerationConfig

# Model information
model_name = "RA-ALTA/es-en-advanced-alpaca-english-L1" #change to different models
language = "French" #change as required
proficiency = "beginner" #change as required
run_id = 2 #change between 1 and 2 as required

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None
)

# Create pipeline
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1
)

# Define default generation config (you can reuse it)
gen_config = GenerationConfig(
    max_new_tokens=300,
    min_new_tokens=250,
    temperature=0.7,
    top_p=0.9,
    do_sample=True,
    repetition_penalty=1.2,
    no_repeat_ngram_size=4,
    pad_token_id=tokenizer.eos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    return_full_text=False
)


print("Model and pipeline loaded. Ready to generate!")

# A1
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities and hobbies you can do in your town at the weekend.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# B1
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# C1
prompt = (
    "### Instruction:\n"
    "Write an article about your family about the question ‘Big family or small family’. You should include whether you have a big or small family, and which you prefer.\n\n "
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# SPANISH:

# SPANISH
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part en diversas actividades y aficiones. Write an article para tu periódico local describing the activities you can do in your town durante el fin de semana.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# SPANISH
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "Tu amiga, Sophia, has emailed you about her recent holiday. Write an email to her, describiéndole tus vacaciones favoritas.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# SPANISH
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "Tu revista local is holding a competition for articles about the question ‘Big family or small family’. Escribe un artículo sobre tu familia. You should include whether you have a big or small family, y cuál prefieres.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# SPANISH
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Spanish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# SPANISH
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Spanish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# SPANISH
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Spanish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# FRENCH:

# FRENCH
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in différentes activités et loisirs. Write an article pour votre journal local describing the activities you can do in your town le week-end.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# FRENCH
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "Votre amie, Sophia, has emailed you about her recent holiday. Write an email to her et décrivez vos vacances préférées.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# FRENCH
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "Votre magazine local is holding a competition for articles about the question 'Big family or small family'. Écrivez un article sur votre famille. You should include whether you have a big or small family, et laquelle vous préférez.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# FRENCH
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in French.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# FRENCH
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in French.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# FRENCH
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in French.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# GERMAN:

# GERMAN
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town wants people an verschiedenen Aktivitäten und Hobbys teilzunehmen. Write an article für Ihre Lokalzeitung describing the activities you can do in your town am Wochenende.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# GERMAN
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "Ihre Freundin, Sophia, has emailed you about her recent holiday. Write an email to her und beschreiben Sie Ihren schönsten Urlaub, den Sie je gemacht haben.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# GERMAN
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "Ihre lokale Zeitschrift is holding a competition for articles about the question 'Big family or small family'. Schreiben Sie einen Artikel über Ihre Familie. You should include whether you have a big or small family, und was Sie bevorzugen.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# GERMAN
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in German.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# GERMAN
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in German.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# GERMAN
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in German.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# POLISH:

# POLISH
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part w różnych zajęciach i hobby. Write an article do lokalnej gazety describing the activities you can do in your town w weekendy.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# POLISH
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "Twoja przyjaciółka, Sophia, has emailed you about her recent holiday. Write an email to her, w którym opiszesz swoje dotychczasowe ulubione wakacje.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# POLISH
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "Twoja lokalna gazeta is holding a competition for articles about the question 'Big family or small family'. Napisz artykuł o swojej rodzinie. You should include whether you have a big or small family, i którą z nich preferujesz.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# POLISH
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Polish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# POLISH
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Polish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# POLISH
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Polish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# TURKISH:

# TURKISH
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town insanların farklı etkinliklere ve hobilere katılmasını istiyor. Yerel gazete için, write an article describing the activities you can do in your town hafta sonu.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# TURKISH
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "Write an email to your friend, Sophia, en sevdiğin tatili anlatan.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# TURKISH
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "Aileniz hakkında bir makale yazın about the question 'Big family or small family'. You should include whether you have a big or small family, ve hangisini tercih ettiğinizi de yazmalısınız.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# TURKISH
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Turkish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# TURKISH
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Turkish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# TURKISH
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Turkish.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# ARABIC:

# ARABIC
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part (في مختلف الأنشطة والهوايات). Write an article (لصحيفتك المحلية) describing the activities you can do in your town (في عطلة نهاية الأسبوع).\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# ARABIC
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "(صديقتك), Sophia, has emailed you about her recent holiday. Write an email to her, (تصف عطلتك المفضلة التي ذهبتَ/ذهبتِ إليها).\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# ARABIC
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "(مجلتك المحلية) is holding a competition for articles about the question ‘Big family or small family’. (اكتب مقالًا عن عائلتك.) You should include whether you have a big or small family, (وأيّهما تفضّل).\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# ARABIC
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Arabic.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# ARABIC
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Arabic.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# ARABIC
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Arabic.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# CHINESE:

# CHINESE
# MIXED LANGUAGE PROMPT STYLE
# A2
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part 在不同的活动和爱好中. Write an article 为您的当地报纸 describing the activities you can do in your town 周末.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# CHINESE
# MIXED LANGUAGE PROMPT STYLE
# B2
prompt = (
    "### Instruction:\n"
    "你的朋友, Sophia, has emailed you about her recent holiday. Write an email to her, 描述一下你最喜欢的假期.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# CHINESE
# MIXED LANGUAGE PROMPT STYLE
# C2
prompt = (
    "### Instruction:\n"
    "你当地的杂志 is holding a competition for articles about the question ‘Big family or small family’. 写一篇关于你家庭的文章. You should include whether you have a big or small family, 你更喜欢哪一个\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# CHINESE
# L2T PROMPT SYLE
# A3
prompt = (
    "### Instruction:\n"
    "Your town wants people to take part in different activities and hobbies. Write an article for your local newspaper describing the activities you can do in your town at the weekend. Think in Chinese.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# CHINESE
# L2T PROMPT SYLE
# B3
prompt = (
    "### Instruction:\n"
    "Your friend, Sophia, has emailed you about her recent holiday. Write an email to her, describing your favourite holiday you have been on. Think in Chinese.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())

# CHINESE
# L2T PROMPT SYLE
# C3
prompt = (
    "### Instruction:\n"
    "Your local magazine is holding a competition for articles about the question ‘Big family or small family’. Write an article about your family. You should include whether you have a big or small family, and which you prefer. Think in Chinese.\n\n"
    "### Response:\n"
)

output = generator(prompt, generation_config=gen_config)
print(output[0]['generated_text'].strip())
